flags: {}
packages:
- .
extra-deps:
- csound-catalog-0.7.3
- csound-expression-5.3.2
- csound-expression-dynamic-0.3.3
- csound-expression-opcodes-0.0.4.0
- csound-expression-typed-0.2.2.0
- csound-sampler-0.0.9.0
- data-fix-cse-0.0.2
- sharc-timbre-0.2
- temporal-media-0.6.3
- wl-pprint-1.2.1
- acme-iot-0.1.0.1@sha256:2e8e331469a7237c6b32bfdaccb44d657a651abe8ad74ca435cfc8549e664859,646
resolver: lts-13.17
