flags: {}
packages:
- .
extra-deps:
- csound-expression-5.3.2
- csound-expression-dynamic-0.3.3
- csound-expression-opcodes-0.0.4.0
- csound-expression-typed-0.2.2.0
- data-fix-cse-0.0.2
- temporal-media-0.6.3
- wl-pprint-1.2.1
resolver: lts-13.17
